highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /posts/:year/:month/:day/:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

url: http://jbctech.com/
baseurl: /
title: James Burke
author: James Burke
description: Personal blog and resume
avatar: profile.png
email: jburke@jbctech.com
github: jbct 
twitter: jbctech
linkedin: jbctech
google_analytics: UA-226894553-1

# needed for travis-ci build
exclude: [vendor]
