# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://jbct.github.io/
baseurl: /
title: James Burke
author: James Burke
description: Personal blog and resume
avatar: profile.png
email: jburke@jbctech.com
github: jbct/jbct.github.io # username
twitter: jbctech
linkedin: jbctech
#stackoverflow: username   #e.g: users/2735833/proton1h1
#medium: username #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
#disqus: username

# needed for travis-ci build
exclude: [vendor]
