highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /posts/:year/:month/:day/:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://www.jbctech.com/
baseurl: '/'
title: James Burke
author: James Burke
description: Personal blog and resume
avatar: profile.png
email: jburke@jbctech.com
github: jbct 
twitter: jbctech
linkedin: jbctech
#stackoverflow: username   #e.g: users/2735833/proton1h1
#medium: username #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
#disqus: username

# needed for travis-ci build
exclude: [vendor]
